[package]
name = "obix"
version = "0.1.0"
edition = "2024"

[features]

fail-on-warnings = []
tracing = ["es-entity/tracing-context"]

[dependencies]
es-entity = { workspace = true }

serde = { workspace = true }
sqlx = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }

[workspace]
resolver = "2"
members = [
  "obix-macros",
]

[workspace.dependencies]

serde = { version = "1.0", features = ["derive"] }
es-entity = "0.10"
anyhow = "1.0"
tokio = { version = "1.48", features = ["rt-multi-thread", "macros"] }
thiserror = "2.0"
sqlx = { version = "0.8", features = ["macros", "runtime-tokio-rustls", "postgres", "uuid", "chrono", "json" ] }
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
