[package]
name = "obix-macros"
version = "0.1.0-dev"
edition = "2024"
license = "Apache-2.0"

[lib]
proc-macro = true

[features]

fail-on-warnings = []
tracing = []

[dependencies]
proc-macro2 = "1.0"
syn = "2.0"
quote = "1.0"
darling = "0.23"
